### ISSUE TITLE
Wall jump: Prevent the player from climbing a single wall

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#106]

**Comment by NathanLovato** [comment]
@DrNeroCF Hey Brad, preventing the player from climbing the wall means we have to prevent horizontal air movement at least temporarily after a wall jump. Should the player have no control for a short while or over a short distance and gain it back after a few moments, or have zero control after a wall jump?

**Comment by NathanLovato** [comment]
Fixed, now you can still wall jump in the wall's direction but you shouldn't be able to climb. Now the question above is still valid, as to make the character always jump away from the wall, depending on what we need gameplay-wise, I have to code it a little differently

**Comment by DrNeroCF** [comment]
In FPA I take away play control until they're falling at a certain speed, but yeah a counter would probably work best.  It only takes a few frames of full speed away from the wall to get a player far enough away that they can't reach the wall again quick enough.  I'll check what's in there.

**Comment by NathanLovato** [comment]
Implementing it isn't an issue, I just think we'd need a wall jump state - the air state is getting too many conditionals otherwise at this point

**Comment by DrNeroCF** [comment]
I would personally only make a new state if there was a specific animation for it, which seems pretty optional to me.  Quick issue, though, jumping while up against a wall latches to the wall before you're moving downward.  Makes the biggest difference when there's a single tile wall and you try to jump over it while pressed against it.

**Comment by NathanLovato** [comment]
That's a bug, I'll get to it
