### ISSUE TITLE
The player has a 1-frame jerky motion upon landing

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#118]
This may also be happening when going from the Run to the idle state. I checked with the camera off already but it’s not clearly visible. We should step through the frames to confirm that. There might be a 1-frame delay in switching states, in which case it would happen with all states.

**Comment by razcore-art** [comment]
Yes, I noticed this too and I'm thinking on the same lines, I think the velocity resets to 0 because it goes through idle: Air -> Idle -> Run instead of Air -> Run.
