### ISSUE TITLE
Pulling away from a wall should cancel the wall jump state

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#133]

**Comment by henriiquecampos** [comment]
I will try to fix it, it should still keep the small delay that allows the wall jump for s brief moment after pulling away from the wall?

**Comment by NathanLovato** [comment]
Iḿ already on it as I need to produce the first chapter asap, i need the player done for the course

**Comment by NathanLovato** [comment]
It's an easy fix but it's a design issue - either we instantly drop from the wall if the player moves in the opposite direction, and make the wall jump work by not pressing a direction key or moving towards the wall, or we keep the timer to allow the player to do opposite direction + jump.

**Comment by NathanLovato** [comment]
Now as Brad said, the ability to climb the wall goes against the core mechanics, as your tool to go up is the hook. So I think we can remove it.
