### ISSUE TITLE
The deadzone on the joystick input should be circular, not on each axis

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#135]
Right now axis input uses Godot's built-in deadzones, that are separate on X and Y axes. We should have a circular deadzone instead.

**Comment by DrNeroCF** [comment]
I see the commit in the master branch's history, but this doesn't appear fixed.  When holding straight up, moving the stick slightly left and right should reflect the subtle movement, since the stick is out of the middle deadzone.

**Comment by DrNeroCF** [comment]
Checking Input.get_action_strength("aim_right") etc, it looks like those use the axis deadzone, do I need to turn those off from the project settings?

**Comment by NathanLovato** [comment]
Your local copy isn't up to date, I've already removed Godot's builtin deadzones

**Comment by NathanLovato** [comment]
As you can see here, the values are set to 0 in the project's latest version: https://github.com/GDquest/godot-metroidvania-2d/commit/9042f2540da3e8090e9f4bd3164d8ac10ad0d999

**Comment by DrNeroCF** [comment]
Weird, thought I reset everything.  Looks like it stuck after re-cloning.  Bah I'll get the hang of this yet.
