### ISSUE TITLE
Bug Report - Character Teleports when colliding

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/godot-metroidvania-2d#14]
When the character collides with a `StaticBody2D` that has its `CollisionShape` in the `Hookable` layer it teleports when the collision is in the air, especially with a strong horizontal velocity.

I can consistently reproduce this behavior

![002 - Bug Report](https://user-images.githubusercontent.com/10171059/57667720-009baa00-75db-11e9-981d-630587aaabe9.gif)

**Comment by NathanLovato** [comment]
Which commit? As I work offline I don't get to push fixes as I make them. it's probably fixed already.

**Comment by NathanLovato** [comment]
Actually yes it's fixed, I remember the collision mask wasn't set to detect hookables on one of the raycasts

**Comment by henriiquecampos** [comment]
I just updated from upstream, commit 9ec02b8 and it the bug persists. Note the Ceiling is set as `one_way_collision = true`

![002 - Bug Report](https://user-images.githubusercontent.com/10171059/57817221-c7874500-7754-11e9-8aea-f38bf9a76c90.gif)

**Comment by henriiquecampos** [comment]
I updated from upstream, commit 9ec02b8, the issue still persists

![002 - Bug Report](https://user-images.githubusercontent.com/10171059/57817446-d15d7800-7755-11e9-84e1-5789437cd658.gif)


I tried rotating the collision shape, since it is one way collision `true` the issue still happens :/

**Comment by NathanLovato** [comment]
That's normal, that's a new mechanic and that's unsupported, 
you've got
to put these platforms on a new physics layer so the ledge 
detector
doesn't catch them.

Henrique Campos <notifications@github.com> writes:

> I just updated from upstream, commit 9ec02b8 and it the bug 
> persists. Note the Ceiling is set as one_way_collision = true
>
> 002 - Bug Report
>
> —
> You are receiving this because you modified the open/close 
> state.
> Reply to this email directly, view it on GitHub, or mute the 
> thread.


-- 
Nathan
https://www.youtube.com/c/gdquest/
