### ISSUE TITLE
PassThroughDetector doesn't work anymore

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#146]
I already split the scene from the player. The code was written before we had the FSM, it needs to be adapted to the current code. The player should be able to go through a pass-through platform when the character is standing on one and the player presses the down key. Other notes:

1. The name should change. The purpose of this node is to allow the player to jump down through pass-through platforms, not to detect pass-through platforms. If it keep this name, the code that manipulate the Player should change
2. It should be tied to a state now we have the FSM in place. It should probably work from both the Idle and Run states, meaning it should maybe belong to the Move node. Or be accessed through `owner`.
3. We should probably remove the NodePath and reference to `Player`, use `owner` instead

**Comment by henriiquecampos** [comment]
I will tackle this.

**Comment by henriiquecampos** [comment]
What do you mean by "belong to the Move node"? If this implies in this node being a child of any state, such state should be a Node2D.
