### ISSUE TITLE
Jump height is too low on Macbook pro 15 inch retina screen

### ISSUE THREAD

**Issue by songproducer** [GDquest/godot-metroidvania-2d#156]

**Comment by songproducer** [comment]
I changed the integer in calculate_jump_velocity from 1.0 to 2.0 (maybe too easy now) but now when up against the wall the jump height is not enough. I am happy to test variables.

**Comment by NathanLovato** [comment]
It's not too low, it's intentional. The main way to move around the world is the hook, the game's core mechanic. The jump allows you to jump up 1 cell.

**Comment by songproducer** [comment]
Hi @NathanLovato I have attached a gif showing the issue.
http://www.giphy.com/gifs/dvV5Bnr7S3J997ovQ5

**Comment by NathanLovato** [comment]
That's normal, the pit is too big. There's no proper level for now in the development version of the project, we have Brad aka DrNeroCF working on levels in his fork.
