### ISSUE TITLE
Movement: Wall jump and slide

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#17]
Add the ability to jump against walls, and have the character slowly slide down slowly while against the wall

**Comment by henriiquecampos** [comment]
With "ability" you mean a new [Skill](https://github.com/GDquest/godot-metroidvania-2d/blob/master/hook!-full-game/src/Player/Hook/Skills/Base.gd)?

If so, Skills are following a State pattern, right?

Could you tell me if these snippets are on the lines for this task?

[WallSlide](https://github.com/pigdevstudio/platform_template/blob/master/source/actors/state_machine/states/wall.gd#L35-L38)
[WallJump](https://github.com/pigdevstudio/platform_template/blob/master/source/actors/state_machine/states/wall.gd#L52-L60)  <- These add a vertical gravity to make the walls behave like a floor, making the character perform an arc similar to as if it was on the floor jumping and moving horizontally.

**Comment by NathanLovato** [comment]
Skill.gd is specific to the hook and likely to go out of the project. Check the Player scene, it uses a state machine now (look for the StateMachine.gd script and Player/**/State.gd)

The character shouldn't be able to climb on a single wall indefinitely imo: the jump is weak in the game, the hook is your main tool. The wall jump's purpose is to help you change direction upon hitting a wall without losing momentum, e.g. to reach a hooking point that's just a little too high otherwise. Another use would be to climb between two walls that are close to one another.

Regarding your snippets, I don't want things like dividing or multiplying the gravity depending on the context, as it makes the motion unreliable: change the world's gravity and the arc of your jumps won't be the same anymore in different states. I prefer the jump to always work the same way, even from a Wall.

For now, you can keep it simple. The wall should mainly feel good and support the core mechanic: the hook.

I would create a Wall state as a child of the Move state, define the wall motion there (e.g. sliding down), and use the Jump state to jump away from the wall. You can already use `StateMachine.transition_to(state, msg={'velocity': ...}` to make the player jump in the direction you want, using the velocity you want.

Check the Move and Jump nodes in the Player scene.
