### ISSUE TITLE
Player: taking damage and stagger

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#21]

**Comment by henriiquecampos** [comment]
Could this be done within a single "hurt" animation and some function calls disabling specific stuff on the nodes? If so it can pretty much be tackled together with #22 quite trivially. Lemme know if this is a good approach

**Comment by NathanLovato** [comment]
Taking damage is +/- already in place. It's a little complex at first glance as it's decoupled from the entities that can take damage. Check HitBox and Stats on the player scene. Damage sources, that can hit a HitBox, can be any DamageSource (an Area2D with DamageSource.gd attached).

Stagger should be a state on the Player that you enter upon taking damage. It can mainly be an animation.
