### ISSUE TITLE
Attacking and inflicting damage with the hook

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#22]
What's left to do for this task:

1. Attaching a DamageSource to the Hook's arrow
1. Making the hook react to clicking on an enemy, but not making the character go to the hook state
1. Making the enemy take damage
1. Giving the hook attack some cooldown

**Comment by henriiquecampos** [comment]
Last week and this weekend I worked with some combat tasks in a game jam and in Kitchen Tales, so these things are quite fresh in my mind. Could you check my entry for [Four Game Devs 1 Art Kit Challenge](https://github.com/henriiquecampos/gamdevs-asset-flip/tree/master/source/actors) and [Kitchen Tales 1st Combat Prototype](https://github.com/pigdevstudio/kitchen-tales/pull/29) to see if these are the directions I can take, or if there is something more specific you want?

**Comment by NathanLovato** [comment]
See the comment I left in #21. I forgot to update these tasks, but the base system to deal and take damage is already in place.

We shouldn't touch this one right now though as the Hook still uses the Skill system that @razcore-art coded and I'm not sure that's the direction to take for it, or we may be able to simplify the code structure.

I'm updating the description above to mention what's left to do.
