### ISSUE TITLE
Debug: label to display information about any entity on screen

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#26]
Design a panel and menu where you can quickly display the state of a property on screen, to monitor what's happening in the code.

**Comment by henriiquecampos** [comment]
I will need more information on this. 

- What kind of properties should be displayed?
- How these properties should be displayed? Is it a simple Label as in the title or a panel or a menu as in the description?
- In case of the menu, what kind of settings should be available to select? Does it have buttons?
- If is a panel, should it display multiple labels for each desired property?
- What are the events that must be monitored from the code? The state of an entity? The game state? The current unlocked skills? The skill just used?

**Comment by NathanLovato** [comment]
The general observation I've had is it's useful to have some values from the game displayed and updating on screen at all times. For instance, the player's velocity and/or move direction, hidden health value, etc. It helps to find some bugs or limitations 

But setting up a signal and connecting this to a new label every time takes time. I'd like to have a solution to display an arbitrary property from an arbritrary node quickly. E.g. `DebugPanel.display(node, property)`, a method that'd create a new label and display the property cleanly in a togglable ingame debug panel or console. No signals, no code in the nodes displayed by the debug menu. I'd like something as simple as possible.

1. Any kind as long as it's a core type. String formatting should take care of the conversion to text.
2. Labels
3. No need for a menu or a complex tool for now.
4. Check the panel that's already in the project, in the src/debug folder.
5. Just properties of objects.
