### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#32]
Implement a checkpoint system that we can use to have the player respawn in different parts of the game.

We'll have to see with the game demo if the checkpoints would be the starts of every frame the player enters, the last save point, the last touched checkpoint object, or something else.

The system should work with some kind of reference to the scene and position or node the players should respawn on.

**Comment by guilhermehto** [comment]
I believe they should be objects in the world. Gives us more control on parts we want to be harder/easier. Once touched/activated can't be reactivated.

**Comment by NathanLovato** [comment]
Something inspired by Castlevania and related games is fine by me. Be it an object we can place anywhere, on the player's path, or in dedicated rooms.

**Comment by henriiquecampos** [comment]
@guilhermehto are you working with that already?

**Comment by NathanLovato** [comment]
Closing this one as we have a more detailed discussion in #74 
I thought the PR would close this issue automatically so I created a new one without checking
