### ISSUE TITLE
AI: Basic scheduling facilities

### ISSUE THREAD

**Issue by Razoric480** [GDquest/godot-metroidvania-2d#35]
While this is optional in most cases when the AI is simple, when the size of the simulation increases, pathfinding requests, heatmap generation, state/behavior tree updates etc can become cumbersome and slow the simulation down, requiring a lot of manual labour to determine when/if a particular AI action needs to run.

A scheduling system alleviates some of that work by centralizing work inside of jobs which can be prioritized and changed with frequency, and offset with a phase.

**Comment by NathanLovato** [comment]
Having a facility like that for this project and future ones, but also to cover often requested topics like optimization is most welcome :)
