### ISSUE TITLE
Dash: movement doesn't work with a gamepad

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#37]
You get a constant stream of input events when using a joystick.

Movement in general is bugged with the gamepad since the change in the code structure

**Comment by razcore-art** [comment]
Are you talking about `_unhandled_input` & related functions? I don't have a gamepad/joystick to test. It's a bit more tricky on `Dash` as we'd have to check for the condition of having the player push the joystick once to the left say (over a strength threshold value), then release (move to 0 position), then move again over threshold to left within `DASH_RESET_TIME`.

**Comment by NathanLovato** [comment]
Don't worry about that. Anyway, the final game shouldn't have a dash as the core mechanic, the hook, already provides more than a dash does. I'll fix it tomorrow before or during the livestream.
