### ISSUE TITLE
Split Player/Skills/Base further based on states

### ISSUE THREAD

**Issue by razcore-art** [GDquest/godot-metroidvania-2d#38]

**Comment by NathanLovato** [comment]
We have concrete needs to help guide code design decisions:
- Trying to stand by the single responsibility principle. Each node should have a precise role. Currently, the Base Skill handles several states by itself and might end up getting bigger if we're not careful
- We need to be able to remove and add skills to have that unlockable nature
- Separating each behavior or state the character can be in into a separate file makes it easier to test (debugger), to record videos, and potentially reuse the code

Note I'll be working on the code tomorrow morning, I'm live for 4 hours, and I may have to mess with it.

**Comment by razcore-art** [comment]
After playing around with the code I'd say that we shouldn't force states and skills to be in 1 to 1 correspondence. This would just end up as a glorified State Machine which isn't what we really need. I can imagine skills themselves having to deal with multiple states.

For example the Air/Ground movement I'd say should stay in one place, a basic movement skill.

You can imagine how this could get a bit funny: what's an `Idle` skill be (1 to 1 with the `"idle"` state)? :)

I'd say we should have these skills at most:
- Move (both `"ground"` & `"air"` states)
- Ledge (`"ledge"` state)
- Dash (as the extra example skill with `"dash"` state)

**Comment by NathanLovato** [comment]
I didn't talk about separating move into different skills, but splitting it up into several files. It *is* already a state machine. And having it all as one file will cause the issues I outlined above. What is move? It's the combination of 3 states: it's a state machine. It could have 3 child nodes.

**Comment by razcore-art** [comment]
`Base` is like a basic *skill*, I should have named it `Basic` perhaps. It's mean to take care the *simple* aka basic motion

**Comment by NathanLovato** [comment]
I got it, but to me, it has several responsibilities: handle idle, ground movement, air movement, hook reaction. It contains several states/behaviors. Now with #39 it will likely get an extra state: hook.

The idea of having Abilities (I find this word more descriptive than skill) as an aggregate is really good. But the basic one needs to be split up at least imo

**Comment by NathanLovato** [comment]
Thinking more about this as I work on the project: how about if we add stagger, death, respawn, etc. states? And adding animations. I'm starting to think a (hierarchical?) state machine will just be easier to handle for the player's movement. Especially as I can get everything working within 1 hour. I've got a working, tested state machine already.

For unlockable states or abilities, we could just have fallback states built into the transitions if some node in the state machine isn't active/hasn't been unlocked by the player.
