### ISSUE TITLE
The base hook mechanic isn't reliable

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#39]
The character currently reacts to the hook with a force applied to it. The force scales based on the distance to the hook. The issue is it's not reliable at all: you may jump way past the hooking point, and the jump (starting velocity) affects the motion, which I feel it should not.

I think the hook should work more like in Flinthook or the old Zelda games now, where it pulls you reliably to the hooking point before taking you back to the air state. In which case a hook state or behavior should take control of the player.

@razcore-art do you think this can work with the components we have for the skills instead of a state machine?

**Comment by razcore-art** [comment]
So after the discussion we had about the abilities/skills let's just agree that we won't talk about components (that's what got me confused at the beginning cause component is a pattern like FSM).

Let's explore HFSM as we discussed, where abilities should be the parent states

**Comment by NathanLovato** [comment]
You can start with a plain state machine, it's easy to turn into an HFSM afterwards if need be.
