### ISSUE TITLE
Pilot tutorial: Tool mode and waypoint system for moving platforms

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#6]
Produce a pilot tutorial to use [the backers' feedback](https://github.com/GDquest/godot-metroidvania-2d/blob/master/docs/feedback-report/report-backers-feedback.org#suggested-improvements-for-tutorials) on the recent form.

Use the work from #5 as a base, but without the hook: this is a beginner tutorial.
The goal is to start to integrate the feedback below to improve the quality of our tutorials. As you'll see they're mostly small improvements that should help make the tutorials feel more structured and cohesive.

Some notes for this one:

- Mention/explain the advantages and drawbacks of Rigid Body physics compared to Kinematic bodies (you can use the 2 prototypes from hook for that)
- No need to add graphics to the game demos, you can rely on colliders (and basic drawing if need be). Again, you can use the hook prototype work as a base, just remove the parts you don't need. Or code a simple demo if you feel it could be faster.
- The target audience for this tut (and upcoming ones) is the target you'll see in the readme.

> The Free courses are for what I would call beginners-plus: amateurs, young programming students, or developers in another domain, e.g. software developers, who have learned the basics of Godot, the basics of GDScript, and put all that in practice in a personal project. The viewer understands basic programming concepts up to what classes and objects are, what a node is at a basic level, and the viewer knows its way around the main areas of the interface.

For the rest, the structure of the tut is up to you. If you need feedback on the outline or anything, you can reply here and ping me anytime.

## Checklist for the tutorial

1.  **Goal and project-driven**: clearly define the teaching goals for the tutorial, explain what the viewer is meant to get out of the tutorial
2.  **Give a summary** of the tutorial's teachings in the intro
    -   Explain and **show** what the viewer is going to learn
    -   Feature a table of contents with timecodes in the video description if the video covers multiple techniques or has distinct chapters
3.  **Remind** the viewer what you covered at the end of the video
4.  Mention **common pitfalls or limitations** of the tool/topic at hand and **provide solutions**

### Text-based content

*I.e. companion text file, pinned comment, video description*

I will take care of this part when preparing the video for release. Could you just keep any link or page you use when creating the tutorial and that you find useful around and paste them in this issue?

1.  **Pre-requisites**: link to content the viewer can use to get started in the description
    - Briefly mention to the viewer they can find pre-requisites and tutorials to watch first in the description
2.  Provide **resources to go further**
    -   Godot docs
    -   Great tutorials from other tutorial makers
    -   General article on the subject, if applicable
3.  **Table of contents** and timecodes to jump to specific sections
4.  Create an **assignment** to help the viewer put what they learned in practice

**Comment by guilhermehto** [comment]
Video is done, it will be on dropbox tomorrow morning - I'll render overnight :smiley: 

## Timecodes

00:20 Demo
01:21 Rigid player scene
03:32 Rigid player script
08:25 Kinematic player scene and script
09:40 Conclusion

## Links used

[RigidBody2D Docs](https://docs.godotengine.org/en/3.1/classes/class_rigidbody2d.html) 
[RigidBody character with Godot 2.2](https://www.youtube.com/watch?v=V4qIOgFBjKY) 
[Finite state machine video - mentioned in video](https://www.youtube.com/watch?v=Ty4wZL7pDME)
[RigidBody character report for metroidvania - mentioned in video](https://github.com/GDquest/godot-metroidvania-2d/blob/master/GAME_CONCEPT.org#test-results)

**Comment by NathanLovato** [comment]
I watched the video, and it's not what I was looking for. It's pretty much the same as every tutorial, and it misses the target audience as you give an overview of the finished code, so it's not beginner-friendly.

![Screenshot from 2019-05-15 11-58-26](https://user-images.githubusercontent.com/12694995/57745693-1b6c3c80-7709-11e9-9b7f-58c2a8633086.png)

There's also probably a misunderstanding regarding what "project-driven" means. If I've written this as part of the checklist, it suggests it's something we don't do already: it means having the viewer create something, not that only you should have a demo, we which always do.

Once again, the code editor's font is small. Is it set to 23 at least as we've discussed before, and as written in the video guidelines?

The tutorial has some value, so let's keep it. But it misses the mark for this task. I think I'll do the pilot video myself, that way we'll have a reference to keep improving upon.

**Comment by guilhermehto** [comment]
So project-driven can be thought of almost as a code along video? Then, yes, I misunderstood it. After finishing the video and watching it I felt like I should've gone for something like firecast's - which we discussed before. Though, I thought it would be better to get your feedback first. 

As for the other points, they were covered:

2. Was done right at the start and while showing the demo
3. Done in the conclusion
4. Throughout the video and during conclusion

Maybe I misunderstood something, I'll watch the video that you linked to us in the discord now. 

The font should be correct, I remember opening the video guidelines and configuring godot before recording. I'll crank the value up next time nonetheless.

**Comment by NathanLovato** [comment]
> As for the other points, they were covered:

Yes and no: as I'm saying above, the goal is to increase the quality of the videos. My problem is the quality of the way in which the points were covered. In the intro, you fade to random clips from other parts of the tutorial that don't help in understanding what the project is about and what the user will learn.

![Screenshot from 2019-05-16 08-41-38](https://user-images.githubusercontent.com/12694995/57816494-79a32900-77b6-11e9-9e53-0dd68dc27fd6.png)

Watch the first 20 seconds of your tut again: the footage doesn't illustrate what you're saying.

I'm not saying that you didn't follow the checklist above, but the whole point isn't to just check the boxes: it's to produce a better tutorial than usual, to integrate the backers' feedback in our tuts. And the video misses the target audience imo, it's not beginner-friendly.

We've talked about copying and pasting code like in the Firebase tutorials, and yes, that's the way to go moving forward. Unless we specifically decide to give a code overview, e.g. for intermediate-level tutorials and up.

Regardless, it's also in the video guidelines: fold and/or remove the code you don't cover (commenting lines could be an option, also I think the copy-paste approach is cleaner).

**Comment by NathanLovato** [comment]
Here's an example of what I meant for the intro: https://www.dropbox.com/s/3cz8o0f2kuvz60k/05-15-godot-waypoints-platform-and-tool.mp4?dl=0

**Comment by guilhermehto** [comment]
Ah, understood! The better approach would've been to already start showing the demo during the intro. The example video helped a lot, thanks! 

From now on I'll stick to the copy paste approach. Might be worth adding more edits to help the viewer focus on what's important as well, for instance, adding those arrows that sometimes you use in your videos. Haven't used them yet, I'll see if there's opportunity in a future video. 

By the way, I'm still open for tasks.

**Comment by NathanLovato** [comment]
Yup, I know, I'm busy clearing up my own todo before going on holidays next week. I was hoping we'd get our hands on a 3d character by now to finish the new features in Godot 3 series. I'll check again with Luciano.

On the metroidvania project, for now, there's only pre-production/design work to do, we're on that with Henrique as we have more exp. with design.

We could use another series to keep the channel alive in the meantime. I asked TwistedLeg if we could use his FPS tutorial and demo as a base for a tut series, and he said he was okay with that (the code needs serious cleanup though https://github.com/TwistedTwigleg/Godot_FPS_Tutorial)

Besides that I don't know, I'm open to suggestions. We could do a round of topic suggestions, so that I can open video tasks you can take on freely while I'm away.

**Comment by NathanLovato** [comment]
Done: https://youtu.be/ZWO2WiH9p9s (I'll prepare it for release next week)
