### ISSUE TITLE
Level design: HookTarget reach area preview in editor

### ISSUE THREAD

**Issue by ZhulanovAA** [GDquest/godot-metroidvania-2d#69]
Maybe it would be nice to add some sort of reach area preview for the HookTargert in the editor showing where player can reach it from? It could make level design easier in some cases

**Comment by henriiquecampos** [comment]
@NathanLovato could this be a plugin that draws a circle using the Hook's length as radius when there are HookTargets selected? Or just a `tool` mode for HookTargets? With the later, it will be harder to get the Hook's length.

**Comment by NathanLovato** [comment]
Already started working on it. I don't see how it's harder to get the hook's length with a `tool` script: it's the node drawing itself, it has access to all its properties and children.

The thing is the hook doesn't have a set length, its length depends on the size of the capsules in the snap detector. Plugin or not, the snap detector needs a method to calculate the length of the hook. Then, all you have to do is to draw a circle with that. A plugin would only complicate things.
