### ISSUE TITLE
Add Checkpoints node to manage checkpoints

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#74]
This node should be the one that keeps track of checkpoints the player discovered.

Consider that there could be checkpoints in scenes that aren't in the level the player is currently, so the Checkpoints node will need some array or dictionary with a reference to all (visited?) checkpoints in the game, the scene they belong to... That's why we can't only use a node group and loop through individual `Checkpoint` nodes to check for unlocked checkpoints

Here is how I would do it:

- Individual checkpoint nodes are part of a checkpoint group
- When the player touches a Checkpoint for the first time, it emits a signal through `Event`
- Checkpoints saves it as a visited checkpoint (dictionary?) along with the scene it belongs to or whatever info we'd need to reliably compare with checkpoints after loading the game. You may need e.g. the scene + the node path

Checkpoints can also have a variable to keep track of the last visited checkpoint, storing the corresponding key in its dict

Checkpoints should have a public interface to get the position of a checkpoint, last visited checkpoint, the list of unlocked checkpoints (for later, imagine a menu to fast travel)

**Comment by NathanLovato** [comment]
@guilhermehto if you want you can tackle that now. The goal is only to add a Checkpoints node. For testing purposes, you can have the game go to the last visited Checkpoint when the player dies. Be sure to use signal and not couple the player node with Checkpoints or any Checkpoint node.

**Comment by henriiquecampos** [comment]
@NathanLovato I was talking with @guilhermehto another day, that maybe it would be a nice architecture to simply use an Area2D with a bunch of CollisionShape2Ds, using said shapes' index to get which is the current checkpoint the player is by using the `area/body_shape_entered`. With that approach, all we have to do, to have the behavior of #74 is to have an internal state in the Area2D that will keep track of which checkpoints, i.e. indices, are discovered, through an array possibly.

Using that approach to add a new checkpoint is just a matter of adding a new CollisionShape2D and move it to the position in the map that we would like to become a checkpoint, meaning there wouldn't be a need for a mediator, like Events, since the Area2D responsible to manage the checkpoints could be a sibling of the Levels.

**Comment by NathanLovato** [comment]
Consider that levels are going to be loaded and unloaded on the fly, so only a few checkpoints will be in the tree. So you'll always have to, upon loading a new level, do something like connect them to the Checkpoints node, or create collision shapes or move checkpoint nodes in the tree.

With Events, you remove the need for setup and cleanup.

**Comment by henriiquecampos** [comment]
Will the checkpoints' location change? If they always stay the same, I think is OK to always have them in the SceneTree, making just the levels/screens themselves loaded in run-time.

For designing purposes we can use the `Load as Placeholder` feature using a low-res/blockage version of a level, to see where exactly the checkpoint will be. Then in runtime, we load the high-res as needed. 

I think this is something we might want in any case to design smoothly with low-res scenes in the editor and run the game with the high-res version. Can be a nice technique to present in the course as well.

**Comment by NathanLovato** [comment]
Yes, the location of checkpoints, just like level or anything in the game world, is subject to change.

**Comment by NathanLovato** [comment]
I'd need to see how this would work. We need an efficient way to edit individual maps or frames, and to place the frames relative to one another, like a world map editor. Having to manually update the checkpoints when you move a room that's supposed to contain a checkpoint around the world sounds like a good way to cause bugs (forgetting to move a checkpoint, the player teleports to it and ends up in a empty part of the world)

**Comment by NathanLovato** [comment]
The reason I'm suggesting to use Events is that we can change the way we design or load levels without breaking the checkpoints system. There's little coupling and it's flexible.

**Comment by henriiquecampos** [comment]
> Yes, the location of checkpoints, just like level or anything in the game world, is subject to change.

I meant in runtime :smile: 

> Having to manually update the checkpoints when you move a room that's supposed to contain a checkpoint around the world sounds like a good way to cause bugs

Yeah, that's for sure is a drawback of this approach. Along with switching children indices, causing it to load the wrong checkpoint from a saved file, but this is unlike to happen.

**Comment by NathanLovato** [comment]
Children indices are more than likely to change: when you remove a level and associated checkpoints.

In general, we should code systems that are flexible and resilient. There are already several reasons for the class to change with the approach you suggest.

**Comment by guilhermehto** [comment]
> When the player touches a Checkpoint for the first time, it emits a signal through Event

Last time I used `class_name` to detect the player from the checkpoint, this time I added a new layer to the player and changed the checkpoint's mask. 

> Checkpoints saves it as a visited checkpoint (dictionary?) along with the scene it belongs to or whatever info we'd need to reliably compare with checkpoints after loading the game. You may need e.g. the scene + the node path

Using an array of dictionaries, saving a reference to the node itself in it felt the best way to go i.e.:
```
visited_checkpoints.append({
	"key": checkpoint.get_path(),
	"checkpoint": checkpoint
})
```
though, I'm not sure how the "restart" of the game is going to happen. 

The other two times I used two different approaches on it and both got scrapped. Now all we do is restart the whole game scene, which again would imply in saving the checkpoint data to the disk _or_ making Checkpoints a singleton. Both of which have already been scrapped. I also thought of having the checkpoint node in the player and have it access it when it dies to re-position itself, but you don't want coupling between these nodes. Not sure how to proceed here. 

> Checkpoints should have a public interface to get the position of a checkpoint

If we save the path to a node we can retrieve it from it directly by accessing the node, if we save the reference itself we can as well.

> last visited checkpoint

As of now we just need to access the last element of the array

> the list of unlocked checkpoints (for later, imagine a menu to fast travel)

All of the checkpoints in the array are the unlocked ones

I feel like I'm missing something :thinking: I can submit a draft PR if you want but as of now just the "systems" are in place, it's not really working as I said before.

**Comment by NathanLovato** [comment]
> though, I'm not sure how the "restart" of the game is going to happen.

It's fine to just have some interface/empty method(s) in place for later.

You can test your checkpoints system locally, e.g. calling a temporary "move_player_to_checkpoint" method upon pressing a key in game.gd. We'll add save, load, etc. later. That's one point of this exercise too: each system should work and be testable in isolation, if you need to couple it to the rest of the game to test it, there's a problem with your code most of the time.
