### ISSUE TITLE
Add ability to jump down on pass-through platforms

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#84]
Currently, there's no way to jump back down after climbing up a pass-through platform. They're the blue tiles on the level design test tileset

![Screenshot from 2019-06-28 09-36-35](https://user-images.githubusercontent.com/12694995/60309330-3ed10b00-9988-11e9-8d11-41bdf9470e36.png)

/!\ Ensure that ledge detector doesn't get in the way, it shouldn't pull the character back up if jumping down near one of the platform's corners

**Comment by henriiquecampos** [comment]
I will start working on that, and I think that I will go with something like I made in this video, any directions?

https://www.youtube.com/watch?v=T704Zrlye2k

**Comment by NathanLovato** [comment]
If it works and the code stays simple that's fine by me :)
