### ISSUE TITLE
Add a dockable plugin for level design

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/godot-metroidvania-2d#95]
The idea is to emulate the Tilemap's dock, where we can select a tile and "paint" it on the scene, just by clicking.

![image](https://user-images.githubusercontent.com/10171059/61130308-c3de1900-a48c-11e9-918b-64f860d76bc8.png)

But in the case of this plugin, we can select whole scenes to "paint".

![image](https://user-images.githubusercontent.com/10171059/61130384-ee2fd680-a48c-11e9-933b-21a3c721640f.png)

The workflow follows:

1. You can drag scenes from the FileSystem to the plugin's dock to add a new `PackedScene` to the "palette"
2. Select a Node in the SceneTree dock as the parent of the scenes you will "paint", i.e. instantiate
3. Select the Scene in the plugin's dock
4. Left click on the Editor's viewport to instantiate the scene at the mouse position
5. Keep clicking to create as many instances of said scene as you want
6. When you finish painting, press ESC to clear the currently selected scene and stop "painting" when you click.

The idea is to keep the FileSystem -> Instance Scene flow, but fixing some inconvenient steps. Currently this workflow goes as follow:

1. Select a Node in the SceneTree dock
1. Select a PackedScene/Texture file
1. Drag it to the Editor's viewport
1. If you, unintentionally, unselected the Node you've selected before, you have to go back to step 1, the plugin shall fix that by always keep a Node to reference as the parent of the instantiated scenes
1. If you managed to instance the scene, either you CTRL+D to duplicate it and keep creating new ones, or you have to start the process again
1. If you want to instantiate new scenes you have to repeat the process from step 1, because the scene you instantiated in step 5 is now selected as the parent of  the next scene you instantiate

**Comment by NathanLovato** [comment]
The design sounds good, go ahead! Open a WIP PR anytime for testing and review.
