### ISSUE TITLE
Death and respawn sequence

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#97]

**Comment by razcore-art** [comment]
What are the requirements for respawn? Would the player have to be respawned at the last checkpoint? Would we have a blinky sort of death animation or something of that sorts? Does the player get multiple lives and has a limit to how many times he/she can respawn? Any other comments would be useful if you can think of anything else.

Some death animation ideas:
1. blink on death and vanish
1. scale down until not too small to be visible
1. combination of the above

Respawn ideas:
1. particle system on appearance
1. scale up (opposite of the above point 2)

**Comment by NathanLovato** [comment]
## On the code's side

There are Die and Respawn states on the player, that trigger corresponding animations on the Player's Skin

## Requirements

For now, don't bother with particles. VFX should come after the main game assets. There are already basic death and respawn animations and states implemented.

This task is about making the death and respawn loop just work. The player should respawn at the last checkpoint, be it the start of the level or the last activated checkpoint.

With level loading and unloading, this also means that we need some kind of special "checkpoint", the player spawn position in this level. In previous demos, I used a dedicated `PlayerSpawn` or `Level/Start` node. This spawn position is not like a regular checkpoint. Imagine that we might give the player the ability to fast travel between checkpoints, that will likely also likely be the place where players can save their progress to the disk.

**Comment by NathanLovato** [comment]
Done with 0320dcf9d1fdda886e3292dafeb371ac4bc9fc11
