### ISSUE TITLE
Add a transition sequence between two levels

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-metroidvania-2d#98]
Have areas that trigger a jump to another level, and a sequence to transition from one level to another

**Comment by razcore-art** [comment]
1. are we going with individual scenes per level? so having a loader in place?
1. are these areas tiny `Area2D` nodes that the player has to reach somehow to trigger level change?
1. by *sequence* do you mean a sort of screen-space animation (like a fade-in/out or so)? or perhaps a loader screen with a loading bar?

**Comment by NathanLovato** [comment]
2. Yes, you reach an area 2d and it triggers the transition sequence, taking control away from the player. You could pause the scene tree to achieve that, having only the ui or transition system and level loader active during the transition.
3. Transitions like combat transitions in OpenRPG or e.g. entering a battle in Pokemon: fade to black with a shader using a greyscale texture, do the unload/load, and fade back in. No need for a loader screen, we'll have short loadings. Keep it simple.

See LevelLoader.gd, and the transition*.* files in Godot open rpg:

1. https://github.com/GDquest/godot-open-rpg/blob/master/godot/assets/shaders/transition.shader
2. https://github.com/GDquest/godot-open-rpg/blob/master/godot/assets/shaders/TransitionColor.gd
